[package]
name = "resolver-tests"
edition.workspace = true

[dependencies]
cargo.workspace = true
cargo-util-schemas.workspace = true
cargo-util.workspace = true
proptest.workspace = true
varisat.workspace = true

[lints]
workspace = true
